### ISSUE TITLE
APK posting

### ISSUE THREAD

**Issue by steenl** [capitancambio/smartphone-bci#12]
Would it be possible to place a complete .apk in the repository of the diagnostic app?  The open source code is truly appreciated, but from my perspective, I would need to setup/learn Android studio to generate the .apk.
Thanks much!

**Comment by ryanlintott** [comment]
Here's a link to the APK:
https://drive.google.com/drive/folders/0B5G8gAXAfXDfWV9Ua1ZRaTkzQTA

**Comment by steenl** [comment]
Thanks much!
